Resources:
  Rule:
    Type: AWS::Config::ConfigRule
    Properties:
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
          - AWS::EC2::Volume
          - AWS::S3::Bucket
          - AWS::RDS::DBInstance
          - AWS::Lambda::Function
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
      InputParameters:
        customFunctionPrefix: tags_costallocation

  RemediationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.lambda_handler
      Architectures:
        - arm64
      Timeout: 60
      Role: "{WILL BE OVERWRITTEN}"

  RemediationFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: ssm.amazonaws.com
      FunctionName: !GetAtt RemediationFunction.Arn

  RemediationDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentFormat: YAML
      DocumentType: Automation
      Content:
        schemaVersion: "0.3"
        assumeRole: "arn:{{ global:AWS_PARTITION }}:iam::{{ global:ACCOUNT_ID }}:role/CostOpt-Automation-{{ global:REGION }}"
        parameters:
          resourceId:
            type: String
          resourceType:
            type: String
        mainSteps:
          - name: InvokeRemediationFunction
            action: aws:invokeLambdaFunction
            inputs:
              FunctionName: "{WILL BE OVERWRITTEN}"
              Payload: |
                {
                  "resourceId": "{{ resourceId }}",
                  "resourceType": "{{ resourceType }}",
                  "configRuleName": "CostOpt-Tags-CostAllocation"
                }
        outputs:
          - InvokeRemediationFunction.Payload

  Remediation:
    Type: AWS::Config::RemediationConfiguration
    DependsOn: Rule
    Properties:
      ConfigRuleName: "{WILL BE OVERWRITTEN}"
      TargetType: SSM_DOCUMENT
      TargetId: "{WILL BE OVERWRITTEN}"
      Parameters:
        resourceId:
          ResourceValue:
            Value: RESOURCE_ID
        resourceType:
          StaticValue:
            Values:
              - RESOURCE_TYPE
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 10
          ErrorPercentage: 10
      Automatic: false
      MaximumAutomaticAttempts: 5
      RetryAttemptSeconds: 600
